spring.datasource.url=${SPRING_DATASOURCE_URL:${JDBC_DATABASE_URL:jdbc:${DATABASE_URL:postgresql://${DB_HOST:${PGHOST}}:${DB_PORT:${PGPORT}}/${DB_NAME:${PGDATABASE}}}}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USER:${PGUSER:}}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:${PGPASSWORD:}}}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=false
spring.thymeleaf.cache=true
server.servlet.session.cookie.secure=true
